version: '3.8'

services:
  app:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:3000'
    environment:
      - GITHUB_API_URL=${GITHUB_API_URL}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  mongo:
    container_name: mongodb
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
